# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.production_order_api import ProductionOrderApi  # noqa: E501
from beanie.rest import ApiException


class TestProductionOrderApi(unittest.TestCase):
    """ProductionOrderApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.production_order_api.ProductionOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_production_order(self):
        """Test case for add_production_order

        """
        pass

    def test_find_production_order_by_id(self):
        """Test case for find_production_order_by_id

        Find Production order by ID  # noqa: E501
        """
        pass

    def test_find_production_orders(self):
        """Test case for find_production_orders

        All production order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
