# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.bill_of_material_api import BillOfMaterialApi  # noqa: E501
from beanie.rest import ApiException


class TestBillOfMaterialApi(unittest.TestCase):
    """BillOfMaterialApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.bill_of_material_api.BillOfMaterialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_bill_of_materials(self):
        """Test case for find_bill_of_materials

        All bill of materials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
