# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.vat_records_api import VatRecordsApi  # noqa: E501
from beanie.rest import ApiException


class TestVatRecordsApi(unittest.TestCase):
    """VatRecordsApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.vat_records_api.VatRecordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_vat_record(self):
        """Test case for add_vat_record

        """
        pass

    def test_find_vat_record_by_id(self):
        """Test case for find_vat_record_by_id

        Find VAT record by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
