# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.stock_location_api import StockLocationApi  # noqa: E501
from beanie.rest import ApiException


class TestStockLocationApi(unittest.TestCase):
    """StockLocationApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.stock_location_api.StockLocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_stock_location(self):
        """Test case for add_stock_location

        """
        pass

    def test_find_stock_location_by_id(self):
        """Test case for find_stock_location_by_id

        Find Stock location by ID  # noqa: E501
        """
        pass

    def test_find_stock_locations(self):
        """Test case for find_stock_locations

        All stock location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
