# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.work_centre_input import WorkCentreInput  # noqa: E501
from beanie.rest import ApiException


class TestWorkCentreInput(unittest.TestCase):
    """WorkCentreInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkCentreInput(self):
        """Test WorkCentreInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.work_centre_input.WorkCentreInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
