# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.partner_address_api import PartnerAddressApi  # noqa: E501
from beanie.rest import ApiException


class TestPartnerAddressApi(unittest.TestCase):
    """PartnerAddressApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.partner_address_api.PartnerAddressApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_partner_address(self):
        """Test case for add_partner_address

        """
        pass

    def test_find_partner_address_by_id(self):
        """Test case for find_partner_address_by_id

        Find Partner address by ID  # noqa: E501
        """
        pass

    def test_find_partner_addresses(self):
        """Test case for find_partner_addresses

        All partner address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
