# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.documents_api import DocumentsApi  # noqa: E501
from beanie.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.documents_api.DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_document(self):
        """Test case for add_document

        """
        pass

    def test_find_document_by_id(self):
        """Test case for find_document_by_id

        Find Document by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
