# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.shipping_centre_input import ShippingCentreInput  # noqa: E501
from beanie.rest import ApiException


class TestShippingCentreInput(unittest.TestCase):
    """ShippingCentreInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShippingCentreInput(self):
        """Test ShippingCentreInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.shipping_centre_input.ShippingCentreInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
