# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.supplier_note import SupplierNote  # noqa: E501
from beanie.rest import ApiException


class TestSupplierNote(unittest.TestCase):
    """SupplierNote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupplierNote(self):
        """Test SupplierNote"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.supplier_note.SupplierNote()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
