# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.purchase_order_api import PurchaseOrderApi  # noqa: E501
from beanie.rest import ApiException


class TestPurchaseOrderApi(unittest.TestCase):
    """PurchaseOrderApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.purchase_order_api.PurchaseOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_purchase_orders(self):
        """Test case for find_purchase_orders

        All purchase order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
