# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.vat_return_api import VatReturnApi  # noqa: E501
from beanie.rest import ApiException


class TestVatReturnApi(unittest.TestCase):
    """VatReturnApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.vat_return_api.VatReturnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_vat_return(self):
        """Test case for add_vat_return

        """
        pass

    def test_find_vat_return_by_id(self):
        """Test case for find_vat_return_by_id

        Find VAT return by ID  # noqa: E501
        """
        pass

    def test_find_vat_returns(self):
        """Test case for find_vat_returns

        All vat return  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
