# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.image_api import ImageApi  # noqa: E501
from beanie.rest import ApiException


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.image_api.ImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_image(self):
        """Test case for add_image

        """
        pass

    def test_find_image_by_id(self):
        """Test case for find_image_by_id

        Find Image by ID  # noqa: E501
        """
        pass

    def test_find_images(self):
        """Test case for find_images

        All image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
