# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.bank_account_api import BankAccountApi  # noqa: E501
from beanie.rest import ApiException


class TestBankAccountApi(unittest.TestCase):
    """BankAccountApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.bank_account_api.BankAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bank_account(self):
        """Test case for add_bank_account

        """
        pass

    def test_find_bank_account_by_id(self):
        """Test case for find_bank_account_by_id

        Find Bank Account by ID  # noqa: E501
        """
        pass

    def test_find_bank_accounts(self):
        """Test case for find_bank_accounts

        All bank accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
