# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.sales_invoice_input import SalesInvoiceInput  # noqa: E501
from beanie.rest import ApiException


class TestSalesInvoiceInput(unittest.TestCase):
    """SalesInvoiceInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSalesInvoiceInput(self):
        """Test SalesInvoiceInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.sales_invoice_input.SalesInvoiceInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
