# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.stock_items_api import StockItemsApi  # noqa: E501
from beanie.rest import ApiException


class TestStockItemsApi(unittest.TestCase):
    """StockItemsApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.stock_items_api.StockItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_stock_item(self):
        """Test case for add_stock_item

        """
        pass

    def test_find_stock_item_by_id(self):
        """Test case for find_stock_item_by_id

        Find Stock item by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
