# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.sales_invoice_api import SalesInvoiceApi  # noqa: E501
from beanie.rest import ApiException


class TestSalesInvoiceApi(unittest.TestCase):
    """SalesInvoiceApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.sales_invoice_api.SalesInvoiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_sales_invoice(self):
        """Test case for add_sales_invoice

        """
        pass

    def test_find_sales_invoice_by_id(self):
        """Test case for find_sales_invoice_by_id

        Find Sales invoice by ID  # noqa: E501
        """
        pass

    def test_find_sales_invoices(self):
        """Test case for find_sales_invoices

        All sales invoice  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
