# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.bank_statements_api import BankStatementsApi  # noqa: E501
from beanie.rest import ApiException


class TestBankStatementsApi(unittest.TestCase):
    """BankStatementsApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.bank_statements_api.BankStatementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bank_statement(self):
        """Test case for add_bank_statement

        """
        pass

    def test_find_bank_statement_by_id(self):
        """Test case for find_bank_statement_by_id

        Find Bank statement by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
