# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.bill_of_material_input import BillOfMaterialInput  # noqa: E501
from beanie.rest import ApiException


class TestBillOfMaterialInput(unittest.TestCase):
    """BillOfMaterialInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillOfMaterialInput(self):
        """Test BillOfMaterialInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.bill_of_material_input.BillOfMaterialInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
