# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.billables_api import BillablesApi  # noqa: E501
from beanie.rest import ApiException


class TestBillablesApi(unittest.TestCase):
    """BillablesApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.billables_api.BillablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_billable(self):
        """Test case for add_billable

        """
        pass

    def test_find_billable_by_id(self):
        """Test case for find_billable_by_id

        Find Billable record by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
