# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.purchase_order_input import PurchaseOrderInput  # noqa: E501
from beanie.rest import ApiException


class TestPurchaseOrderInput(unittest.TestCase):
    """PurchaseOrderInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPurchaseOrderInput(self):
        """Test PurchaseOrderInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.purchase_order_input.PurchaseOrderInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
