# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.goods_received_note import GoodsReceivedNote  # noqa: E501
from beanie.rest import ApiException


class TestGoodsReceivedNote(unittest.TestCase):
    """GoodsReceivedNote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoodsReceivedNote(self):
        """Test GoodsReceivedNote"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.goods_received_note.GoodsReceivedNote()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
