# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.beanie_tasks_api import BeanieTasksApi  # noqa: E501
from beanie.rest import ApiException


class TestBeanieTasksApi(unittest.TestCase):
    """BeanieTasksApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.beanie_tasks_api.BeanieTasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_beanie_task(self):
        """Test case for add_beanie_task

        """
        pass

    def test_find_beanie_task_by_id(self):
        """Test case for find_beanie_task_by_id

        Find Beanie task by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
