# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.stock_category import StockCategory  # noqa: E501
from beanie.rest import ApiException


class TestStockCategory(unittest.TestCase):
    """StockCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStockCategory(self):
        """Test StockCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.stock_category.StockCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
