# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.bank_statement_api import BankStatementApi  # noqa: E501
from beanie.rest import ApiException


class TestBankStatementApi(unittest.TestCase):
    """BankStatementApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.bank_statement_api.BankStatementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_bank_statements(self):
        """Test case for find_bank_statements

        All bank statement  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
