# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.supplier_addresses_api import SupplierAddressesApi  # noqa: E501
from beanie.rest import ApiException


class TestSupplierAddressesApi(unittest.TestCase):
    """SupplierAddressesApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.supplier_addresses_api.SupplierAddressesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_supplier_address(self):
        """Test case for add_supplier_address

        """
        pass

    def test_find_supplier_address_by_id(self):
        """Test case for find_supplier_address_by_id

        Find Supplier address by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
