# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.shipping_centres_api import ShippingCentresApi  # noqa: E501
from beanie.rest import ApiException


class TestShippingCentresApi(unittest.TestCase):
    """ShippingCentresApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.shipping_centres_api.ShippingCentresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_shipping_centre(self):
        """Test case for add_shipping_centre

        """
        pass

    def test_find_shipping_centre_by_id(self):
        """Test case for find_shipping_centre_by_id

        Find Shipping centre by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
