# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.supplier_address_api import SupplierAddressApi  # noqa: E501
from beanie.rest import ApiException


class TestSupplierAddressApi(unittest.TestCase):
    """SupplierAddressApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.supplier_address_api.SupplierAddressApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_supplier_addresses(self):
        """Test case for find_supplier_addresses

        All supplier address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
