# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.models.bill_of_material import BillOfMaterial  # noqa: E501
from beanie.rest import ApiException


class TestBillOfMaterial(unittest.TestCase):
    """BillOfMaterial unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillOfMaterial(self):
        """Test BillOfMaterial"""
        # FIXME: construct object with mandatory attributes with example values
        # model = beanie.models.bill_of_material.BillOfMaterial()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
