# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.nominal_accounts_api import NominalAccountsApi  # noqa: E501
from beanie.rest import ApiException


class TestNominalAccountsApi(unittest.TestCase):
    """NominalAccountsApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.nominal_accounts_api.NominalAccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_nominal_account(self):
        """Test case for add_nominal_account

        """
        pass

    def test_find_nominal_account_by_id(self):
        """Test case for find_nominal_account_by_id

        Find Nominal account by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
