# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.2
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import beanie
from beanie.api.bill_of_materials_api import BillOfMaterialsApi  # noqa: E501
from beanie.rest import ApiException


class TestBillOfMaterialsApi(unittest.TestCase):
    """BillOfMaterialsApi unit test stubs"""

    def setUp(self):
        self.api = beanie.api.bill_of_materials_api.BillOfMaterialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bill_of_material(self):
        """Test case for add_bill_of_material

        """
        pass

    def test_find_bill_of_material_by_id(self):
        """Test case for find_bill_of_material_by_id

        Find Bill of Materials by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
