# coding: utf-8

"""
    Beanie ERP API

    An API specification for interacting with the Beanie ERP system  # noqa: E501

    OpenAPI spec version: 0.8
    Contact: dev@bean.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductionOrderLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'datetime',
        'member': 'str',
        'message': 'str'
    }

    attribute_map = {
        '_date': 'date',
        'member': 'member',
        'message': 'message'
    }

    def __init__(self, _date=None, member=None, message=None):  # noqa: E501
        """ProductionOrderLog - a model defined in Swagger"""  # noqa: E501

        self.__date = None
        self._member = None
        self._message = None
        self.discriminator = None

        self._date = _date
        self.member = member
        self.message = message

    @property
    def _date(self):
        """Gets the _date of this ProductionOrderLog.  # noqa: E501


        :return: The _date of this ProductionOrderLog.  # noqa: E501
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this ProductionOrderLog.


        :param _date: The _date of this ProductionOrderLog.  # noqa: E501
        :type: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def member(self):
        """Gets the member of this ProductionOrderLog.  # noqa: E501


        :return: The member of this ProductionOrderLog.  # noqa: E501
        :rtype: str
        """
        return self._member

    @member.setter
    def member(self, member):
        """Sets the member of this ProductionOrderLog.


        :param member: The member of this ProductionOrderLog.  # noqa: E501
        :type: str
        """
        if member is None:
            raise ValueError("Invalid value for `member`, must not be `None`")  # noqa: E501

        self._member = member

    @property
    def message(self):
        """Gets the message of this ProductionOrderLog.  # noqa: E501


        :return: The message of this ProductionOrderLog.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ProductionOrderLog.


        :param message: The message of this ProductionOrderLog.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductionOrderLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
